### ISSUE TITLE
ESP8266WiFi.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by deepikavira** [morrissinger/ESP8266-Websocket#11]
Hi I am facing this error. Can someone tell me where to get the ESP8266WiFi.h file from. I don't see it in my libraries folder.

**Comment by lizard43** [comment]
Have you installed the esp8266 board package into Arduino IDE?

https://github.com/esp8266/Arduino/blob/master/README.md

**Comment by deepikavira** [comment]
I actually didn't install the esp8266 board package. Now I have it installed and the problem is solved. Thanks.
