### ISSUE TITLE
Need connecting....

### ISSUE THREAD

**Issue by toastedmango** [morrissinger/ESP8266-Websocket#19]
Hello,
Thanks for making this.  I'm very new to the arduino world, have been reading on several websites about using using esp8266 and websockets.  I'm hoping someone can help me,  After uploading my sketch to the esp8266, I was wondering how do you set up the esp8266 to the serial monitor in the arduino IDE so  I can hopefully see what's coming through.  Presently I just show a blue light coming off of the esp8266, but I need sometype of monitor to see how what text is spitting out.  Thanks in advance...

**Comment by morrissinger** [comment]
You should connect an FTDI interface between the serial interface of the ESP and the USB interface of your computer. Hope that helps. Closing the issue as it's not really an issue with the repo.
